services:
  app:
    build: .
    container_name: user-service
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - 8080:8080
  postgres:
    image: postgres:17.2-alpine
    container_name: user-service-db
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
  redis:
    image: redis:latest
    container_name: user-service-redis
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data
volumes:
  pg_data:
  redis_data:
