services:
  app:
    build: .
    container_name: user-service
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  postgres:
    image: postgres:17.2-alpine
    container_name: user-service-db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
volumes:
  pg_data:
