spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/user_service_db
        username: user_service_app
        password: user_service123
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate  # Use validate or none in production
        properties:
            hibernate:
                format_sql: true   # Formats SQL output for better readability in dev,
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false  # Keep off in production
    flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:db/migration

security:
    ## Local development
    user: admin
    password: admin
    jwt:
        secret-key: ${JWT_SECRET_KEY:s3cr3tK3y12345}
        expiration: 3600000 # 1 hour


##logging:
##    level:
##        org.hibernate.SQL: DEBUG   # Enable SQL logging only for debugging
##        org.flywaydb: DEBUG
##        org.springframework.security: TRACE
##        com.annyai: TRACE
##        springframework.web: TRACE