spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/${POSTGRES_DB}
    username: ${APP_USER}
    password: ${APP_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # Use validate or none in production
    properties:
      hibernate:
        format_sql: false   # Formats SQL output for better readability in dev
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false  # Keep off in production
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-ms: 3600000 # 1 hour

logging:
  level:
    org.hibernate.SQL: DEBUG   # Enable SQL logging only for debugging
