spring:
    datasource:
        url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
        username: ${APP_USER}
        password: ${APP_PASSWORD}
        driver-class-name: org.postgresql.Driver
    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}
            timeout: 2s
            password: ${REDIS_PASSWORD}
            ssl:
                enabled: true
    jpa:
        hibernate:
            ddl-auto: validate  # Use validate or none in production
        properties:
            hibernate:
                format_sql: false   # Formats SQL output for better readability in dev
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false  # Keep off in production
    flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:db/migration

security:
    jwt:
        secret-key: ${JWT_SECRET_KEY}
        expiration: 60m